api_token: # <your_openrouter_api_token>
# Optionally, you can specify a different model to use
# for commit message generation with:
#
#   model: <valid_model_id_from_openrouter>
#
# If the `model:` parameter is absent or left blank, then
# the default (`qwen/qwen3-30b-a3b:free`) will be used.
