name: Publish to PyPI
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup-uv
        uses: astral-sh/setup-uv@v5

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: uv-sync
        run: uv sync --all-extras --dev

      - name: uv-build
        run: uv build

      - name: uv-publish
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
