name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync dependencies
        run: uv sync --all-extras --dev --locked

      - name: Run tests
        run: uv run pytest --cov=acmsg --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.4.2
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Check types with mypy
        run: uv run mypy src/acmsg
