name: Run Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup uv
        uses: astral-sh/setup-uv@v6.0.1
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: "pyproject.toml"

      - name: Run uv sync
        run: uv sync --all-extras --dev

      - name: Run pytest
        run: uv run pytest --cov=acmsg --cov-report=xml

      - name: Run mypy
        run: uv run mypy src/acmsg

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.4.2
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
